// import 'package:cloud_firestore/cloud_firestore.dart';

// Future<void> addBulkData() async {
//   // Create a reference to Firestore
//   final FirebaseFirestore firestore = FirebaseFirestore.instance;

//   // Create a batch
//   WriteBatch batch = firestore.batch();

//   // Your bulk data (list of maps)
//   List<String> bulkData = [
//     "Sweat is just fat crying.",
//     "The only bad workout is the one that didn't happen.",
//     "Push yourself because no one else is going to do it for you.",
//     "Success starts with self-discipline.",
//     "No pain, no gain.",
//     "Sore today, strong tomorrow.",
//     "Don't stop until you're proud.",
//     "You don't have to be great to start, but you have to start to be great.",
//     "Your body can stand almost anything. It’s your mind you have to convince.",
//     "Train like a beast, look like a beauty.",
//     "Excuses don’t burn calories.",
//     "When you feel like quitting, think about why you started.",
//     "The pain you feel today will be the strength you feel tomorrow.",
//     "Fitness is not about being better than someone else. It’s about being better than you used to be.",
//     "It never gets easier. You just get better.",
//     "Fitness is not a destination, it’s a way of life.",
//     "Do something today that your future self will thank you for.",
//     "Good things come to those who sweat.",
//     "Don’t limit your challenges. Challenge your limits.",
//     "Take care of your body. It’s the only place you have to live.",
//     "You don’t get the ass you want by sitting on it.",
//     "Strive for progress, not perfection.",
//     "Believe you can and you’re halfway there.",
//     "The only way to define your limits is by going beyond them.",
//     "Wake up with determination, go to bed with satisfaction.",
//     "You miss 100% of the workouts you don’t do.",
//     "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
//     "Motivation is what gets you started. Habit is what keeps you going.",
//     "Fall in love with taking care of yourself.",
//     "You didn’t come this far to only come this far.",
//     "A one-hour workout is 4% of your day. No excuses.",
//     "Work hard in silence. Let success be your noise.",
//     "The body achieves what the mind believes.",
//     "Make yourself a priority.",
//     "Don’t wish for a good body, work for it.",
//     "The only person you are destined to become is the person you decide to be.",
//     "Your life does not get better by chance, it gets better by change.",
//     "Make every workout count.",
//     "Discipline is the bridge between goals and accomplishments.",
//     "The difference between the impossible and the possible lies in a person’s determination.",
//     "Don't quit. Suffer now and live the rest of your life as a champion.",
//     "It's going to be a journey. It’s not a sprint to get in shape.",
//     "You are your only limit.",
//     "Take it one workout at a time.",
//     "Sweat now, shine later.",
//     "Respect your body. It’s the only one you get.",
//     "You are what you do, not what you say you’ll do.",
//     "Pain is temporary. Quitting lasts forever.",
//     "Strong is the new skinny.",
//     "Believe in yourself and all that you are.",
//     "The best project you’ll ever work on is you.",
//     "Fitness is like a relationship. You can’t cheat and expect it to work.",
//     "Don’t let the scale define you. Be active, be healthy, be happy.",
//     "You don’t find willpower. You create it.",
//     "Fitness isn’t about being better than someone else, it’s about being better than you used to be.",
//     "Be stronger than your excuses.",
//     "Fitness is a journey, not a destination.",
//     "A healthy lifestyle is something you refine over time.",
//     "Fitness is 100% mental. Your body won’t go where your mind doesn’t push it.",
//     "You don’t have to be extreme, just consistent.",
//     "You get what you work for, not what you wish for.",
//     "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
//     "Fitness is not about being better than others, it’s about becoming better than you used to be.",
//     "Fitness is a marathon, not a sprint.",
//     "You don’t have to be perfect to be amazing.",
//     "There’s no secret formula. I lift heavy, work hard, and aim to be the best.",
//     "No one has ever drowned in sweat.",
//     "A year from now, you’ll wish you had started today.",
//     "It always seems impossible until it’s done.",
//     "If it doesn’t challenge you, it won’t change you.",
//     "Dedicate yourself to becoming your best.",
//     "Fitness is not an option, it’s a lifestyle.",
//     "You’re only one workout away from a good mood.",
//     "Your success is found in your daily routine.",
//     "When you feel like quitting, think about why you started.",
//     "The difference between try and triumph is a little 'umph.'",
//     "Strength does not come from physical capacity. It comes from an indomitable will.",
//     "Nothing worth having comes easy.",
//     "Your health is an investment, not an expense.",
//     "Stop saying tomorrow. Start now.",
//     "You’re only one workout away from a better mood.",
//     "Keep going. Every workout gets you closer to your goals.",
//     "Fit is not a destination, it’s a way of life.",
//     "You don’t need to go fast, you just need to go.",
//     "Success isn’t always about greatness. It’s about consistency.",
//     "Excuses are the nails used to build a house of failure.",
//     "It’s not about having time, it’s about making time.",
//     "Every day is another chance to get stronger.",
//     "Dream big, work hard, stay focused, and surround yourself with good people.",
//     "What seems hard today will one day be your warm-up.",
//     "Your body can stand almost anything. It’s your mind that you have to convince.",
//     "Exercise is the most potent and underutilized antidepressant.",
//     "Train like a beast to look like a beauty.",
//     "Never miss a Monday workout.",
//     "The only time success comes before work is in the dictionary.",
//     "Exercise not only changes your body, it changes your mind, your attitude, and your mood.",
//     "Pain is temporary. Quitting lasts forever.",
//     "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
//     "The pain you feel today will be the strength you feel tomorrow.",
//     "The body achieves what the mind believes.",
//     "When you feel like stopping, think about why you started.",
//     "Don’t let yesterday take up too much of today.",
//     "Your body hears everything your mind says.",
//     "Focus on progress, not perfection.",
//     "Once you see results, it becomes an addiction.",
//     "You have to believe in yourself when no one else does.",
//     "Good things come to those who sweat.",
//     "Make each day your masterpiece.",
//     "Motivation gets you started. Habit keeps you going.",
//     "Don’t wait for opportunity. Create it.",
//     "Fitness is a lifestyle, not a short-term fix.",
//     "Do it for the 'holy shit, you got hot!' moments.",
//     "Work hard in silence, let success be your noise.",
//     "Stay patient and trust your journey.",
//     "Stop doubting yourself, work hard, and make it happen.",
//     "What doesn’t kill you makes you stronger.",
//     "The only bad workout is the one that didn’t happen.",
//     "Commit to be fit.",
//     "Train insane or remain the same.",
//     "Don’t count the days, make the days count.",
//     "The difference between the impossible and the possible lies in a person’s determination.",
//     "Fitness is not a punishment; it’s a blessing.",
//     "If it doesn’t challenge you, it doesn’t change you.",
//     "The harder the battle, the sweeter the victory.",
//     "The greatest wealth is health.",
//     "You’re stronger than you think.",
//     "You can’t out-train a bad diet.",
//     "Get comfortable with being uncomfortable.",
//     "The best way to predict the future is to create it.",
//     "Your speed doesn’t matter. Forward is forward.",
//     "One workout at a time, one day at a time, one meal at a time.",
//     "Don't stop when you're tired, stop when you're done.",
//     "Train your mind and your body will follow.",
//     "If you still look cute at the end of your workout, you didn’t train hard enough.",
//     "Run when you can, walk if you have to, crawl if you must; just never give up.",
//     "If you want something you’ve never had, you must be willing to do something you’ve never done.",
//     "Don't be afraid of being a beginner.",
//     "Be stronger than your strongest excuse.",
//     "Sweat, smile, repeat.",
//     "Stop wishing, start doing.",
//     "Life begins at the end of your comfort zone.",
//     "Work hard, stay consistent, and be patient.",
//     "Don’t decrease the goal, increase the effort.",
//     "Success is the sum of small efforts, repeated day in and day out.",
//     "You have to be at your strongest when you’re feeling at your weakest.",
//     "Make today so awesome that yesterday gets jealous.",
//     "The harder you work for something, the greater you’ll feel when you achieve it.",
//     "Hustle for that muscle.",
//     "Your fitness is 100% mental. Your body won’t go where your mind doesn’t push it.",
//     "Believe you can and you’re halfway there.",
//     "When it burns, is when you’re just getting started.",
//     "Stop being afraid of what could go wrong and think of what could go right.",
//     "Excuses don’t get results.",
//     "Get fit in the gym. Lose weight in the kitchen.",
//     "Exercise is therapy.",
//     "If you don’t like starting over, stop giving up.",
//     "Fitness is like marriage. You can’t cheat on it and expect it to work.",
//     "Success is what happens after you’ve survived all your mistakes.",
//     "When you want to give up, remember why you started.",
//     "It’s not just about the body you build, but the mind you strengthen.",
//     "Don't let anyone outwork you."
//     // Add more quotes if needed
//   ];

//   // Loop through data and add to batch
//   for (var data in bulkData) {
//     // Create a document reference (adjust to your Firestore collection)
//     DocumentReference docRef = firestore.collection("quotes").doc();
//     // Add the operation to the batch
//     batch.set(docRef, {"quote": data});
//   }

//   // Commit the batch
//   try {
//     await batch.commit();
//     print('Batch write successful');
//   } catch (e) {
//     print('Error writing batch: $e');
//   }
// }
